"""Add media fields to Post

Revision ID: 9c6af0a1e535
Revises: c908b36f3315
Create Date: 2025-11-23 11:17:12.236731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c6af0a1e535'
down_revision = 'c908b36f3315'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('media_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('media_type')
        batch_op.drop_column('media_filename')

    # ### end Alembic commands ###
